"""Add fall events and update models for phase 10

Revision ID: 1fc9a5ed9ecc
Revises: 5d6ed801d6d4
Create Date: 2026-09-28 22:08:25.768716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fc9a5ed9ecc'
down_revision: Union[str, Sequence[str], None] = '5d6ed801d6d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fall_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cattle_id', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('peak_acceleration', sa.Float(), nullable=True),
    sa.Column('activity_score', sa.Float(), nullable=True),
    sa.Column('fall_confidence', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.cattle_id'], name=op.f('fk_fall_events_cattle_id_cattle')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fall_events'))
    )
    with op.batch_alter_table('fall_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fall_events_cattle_id'), ['cattle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fall_events_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_fall_events_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_fall_events_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('type', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('message', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('threshold', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('acknowledged_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_timestamp'))
        batch_op.create_index(batch_op.f('ix_alerts_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_type'), ['type'], unique=False)
        batch_op.drop_column('parameter')
        batch_op.drop_column('alert_type')
        batch_op.drop_column('actual_value')
        batch_op.drop_column('timestamp')

    with op.batch_alter_table('sensor_calibrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('buffer_1', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buffer_1_voltage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buffer_2', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('buffer_2_voltage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('slope', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('intercept', sa.Float(), nullable=True))

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('peak_acceleration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_column('peak_acceleration')

    with op.batch_alter_table('sensor_calibrations', schema=None) as batch_op:
        batch_op.drop_column('intercept')
        batch_op.drop_column('slope')
        batch_op.drop_column('buffer_2_voltage')
        batch_op.drop_column('buffer_2')
        batch_op.drop_column('buffer_1_voltage')
        batch_op.drop_column('buffer_1')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('actual_value', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('alert_type', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('parameter', sa.VARCHAR(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_alerts_type'))
        batch_op.drop_index(batch_op.f('ix_alerts_device_id'))
        batch_op.create_index(batch_op.f('ix_alerts_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('acknowledged_at')
        batch_op.drop_column('confidence')
        batch_op.drop_column('threshold')
        batch_op.drop_column('value')
        batch_op.drop_column('message')
        batch_op.drop_column('type')
        batch_op.drop_column('device_id')

    with op.batch_alter_table('fall_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fall_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_fall_events_id'))
        batch_op.drop_index(batch_op.f('ix_fall_events_deleted'))
        batch_op.drop_index(batch_op.f('ix_fall_events_cattle_id'))

    op.drop_table('fall_events')
    # ### end Alembic commands ###
