"""Add cattle extended fields

Revision ID: 5d6ed801d6d4
Revises: ba10a61a0168
Create Date: 2026-09-28 20:20:28.136284

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d6ed801d6d4'
down_revision: Union[str, Sequence[str], None] = 'ba10a61a0168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('tag_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lactation_stage', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('pregnancy_status', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('medical_history', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cattle_tag_id'), ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cattle_tag_id'))
        batch_op.drop_column('medical_history')
        batch_op.drop_column('pregnancy_status')
        batch_op.drop_column('lactation_stage')
        batch_op.drop_column('tag_id')
        batch_op.drop_column('weight')
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
