"""Add device assignments for assignment history

Revision ID: a98230bdea29
Revises: 1fc9a5ed9ecc
Create Date: 2026-09-28 22:09:28.127361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a98230bdea29'
down_revision: Union[str, Sequence[str], None] = '1fc9a5ed9ecc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(), nullable=True),
    sa.Column('cattle_id', sa.String(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('removed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['cattle_id'], ['cattle.cattle_id'], name=op.f('fk_device_assignments_cattle_id_cattle')),
    sa.ForeignKeyConstraint(['device_id'], ['devices.device_id'], name=op.f('fk_device_assignments_device_id_devices')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_assignments'))
    )
    with op.batch_alter_table('device_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_assignments_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_assignments_cattle_id'), ['cattle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_assignments_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_assignments_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_assignments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_assignments_removed_at'), ['removed_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_assignments_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_assignments_status'))
        batch_op.drop_index(batch_op.f('ix_device_assignments_removed_at'))
        batch_op.drop_index(batch_op.f('ix_device_assignments_id'))
        batch_op.drop_index(batch_op.f('ix_device_assignments_device_id'))
        batch_op.drop_index(batch_op.f('ix_device_assignments_deleted'))
        batch_op.drop_index(batch_op.f('ix_device_assignments_cattle_id'))
        batch_op.drop_index(batch_op.f('ix_device_assignments_assigned_at'))

    op.drop_table('device_assignments')
    # ### end Alembic commands ###
