"""Initial migration

Revision ID: ba10a61a0168
Revises: 
Create Date: 2026-09-28 20:18:31.845723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba10a61a0168'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_activity_cattle_id_cattle'), 'cattle', ['cattle_id'], ['cattle_id'])

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_alert_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_alert_type'), ['alert_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_alerts_cattle_id_cattle'), 'cattle', ['cattle_id'], ['cattle_id'])

    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_cattle_deleted'), ['deleted'], unique=False)

    with op.batch_alter_table('feed_consumption', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_feed_consumption_deleted'), ['deleted'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_feed_consumption_cattle_id_cattle'), 'cattle', ['cattle_id'], ['cattle_id'])

    with op.batch_alter_table('milk_production', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_milk_production_deleted'), ['deleted'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_milk_production_cattle_id_cattle'), 'cattle', ['cattle_id'], ['cattle_id'])

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_predictions_deleted'), ['deleted'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_predictions_reading_id_sensor_readings'), 'sensor_readings', ['reading_id'], ['id'])
        batch_op.drop_column('bpm_status')

    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('acceleration_magnitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('activity_state', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('activity_score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('fall_detected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('fall_confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('deleted', sa.Boolean(), nullable=True))
        batch_op.create_index('idx_cattle_timestamp', ['cattle_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_deleted'), ['deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_sensor_readings_device_id'), ['device_id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_sensor_readings_cattle_id_cattle'), 'cattle', ['cattle_id'], ['cattle_id'])
        batch_op.create_foreign_key(batch_op.f('fk_sensor_readings_device_id_devices'), 'devices', ['device_id'], ['device_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_sensor_readings_device_id_devices'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_sensor_readings_cattle_id_cattle'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sensor_readings_device_id'))
        batch_op.drop_index(batch_op.f('ix_sensor_readings_deleted'))
        batch_op.drop_index('idx_cattle_timestamp')
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('fall_confidence')
        batch_op.drop_column('fall_detected')
        batch_op.drop_column('activity_score')
        batch_op.drop_column('activity_state')
        batch_op.drop_column('acceleration_magnitude')
        batch_op.drop_column('device_id')

    with op.batch_alter_table('predictions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bpm_status', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_predictions_reading_id_sensor_readings'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_predictions_deleted'))
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('milk_production', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_milk_production_cattle_id_cattle'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_milk_production_deleted'))
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('feed_consumption', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_feed_consumption_cattle_id_cattle'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_feed_consumption_deleted'))
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('cattle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cattle_deleted'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_alerts_cattle_id_cattle'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_deleted'))
        batch_op.drop_index(batch_op.f('ix_alerts_alert_type'))
        batch_op.drop_index('idx_alert_status_severity')
        batch_op.drop_column('deleted')
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_activity_cattle_id_cattle'), type_='foreignkey')

    # ### end Alembic commands ###
